name: Build

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install --legacy-peer-deps
          export NODE_OPTIONS=--openssl-legacy-provider

      - name: Build
        run: npm run build
